name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Ejecuta el pipeline cuando haya cambios en la rama 'main'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod 
    steps:
      # Paso 1: Configurar Node.js
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Asegúrate de usar la versión adecuada

      - name: Install dependencies and generate Prisma client
        run: |
          npm install
          npx prisma generate

      # Paso 2: Compilar TypeScript y empaquetar
      - name: Build and package
        run: |
          npm run build:lambda
          cp -r node_modules/.prisma dist/
          cp -r node_modules/@prisma dist/node_modules/
          zip -r backend.zip dist/

      # Paso 3: Desplegar en Lambda
      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name backend --zip-file fileb://backend.zip
